#! /usr/bin/env ruby

$: << File.expand_path(File.dirname(__FILE__) + "/lib")

require File.expand_path(File.dirname(__FILE__) + "/gems/bundler/setup")
require "cleantracker/text_ui"

Cleantracker::TextUi.run(ARGV)